homepage_for_portfolio
johnspeny/JohnSpenyPortifolio pull request #1
Opened 2021-07-09 15:21 UTC by johnspeny

- Created images folder to hold images

- icon folder for SVG icons
- index.html with proper link to css file

2021-07-09 20:37 UTC, AshakaE requested changes
### Hi  @johnspeny 👋 , 

You have done an impressive job so far! 👌.  However, there are some issues that you still need to work on to go to the next project but you are almost there!

### Highlights 🚀 
- Great implementation of the `flexbox`
- You crafted a robust README file
- Your pull request is descriptive but can use some more work
- Proper Git flow 

## Required Changes ♻️
_Check the comments under the review._


### Optional suggestions
_Moving forward please make use of present tense for commit messages and pull request description_ 
example instead of `created images` rather `Create images` .

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2021-07-09 21:19 UTC, johnspeny commented on index.html
> +            <span class="headline__nameTwo">I'm a software developer</span></h2>
This will break my css. its best left like that.

2021-07-09 21:19 UTC, johnspeny commented on index.html
> +            <h2> <span class="headline__nameOne">Hey there. I'm Okker John.</span><br />
Done

2021-07-09 21:20 UTC, johnspeny commented on index.html
> +        </div>
Done

2021-07-09 21:20 UTC, johnspeny commented on index.html
> +        <h3 class="header__logo">johnspeny</h3>
Done

2021-07-09 21:20 UTC, johnspeny commented on style.css
> +}
Done

2021-07-09 21:21 UTC, johnspeny commented
All changes made except changing span to p tags

2021-07-09 21:45 UTC, ahmetbozaci requested changes
# STATUS: Changes Required  ♻️ 

## Hello @johnspeny ✋🏼  Nice done with working on last review.However there are still some issues you should fix. Please fix them then your project will be approved.


### ♻️ Request changes ♻️
 
_**Check the comment about that  under the review.**_


### OPTIONAL SUGGESTIONS

#### These are optional 

- [ ] Your commit messages should always start  with capital letters and you should write an imperative tense. I see some of them are not like that. You can change them by using `git rebase`. Please watch this [video](https://www.loom.com/share/00771f369b7b47fc968c019ecf0d3ba6) and check this [article](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8/)
- [ ]  Instead of using pictures for icons you can use icons from [font-awesome](https://fontawesome.com/start). 
### Cheers and Happy coding! 💻 👏
![cat on laptop](https://media.giphy.com/media/QHE5gWI0QjqF2/giphy.gif)
___
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form.](https://airtable.com/shrQAqnBwek5a0O0s)_
___
_If anything seems to be unclear to you, reach out and ask anything by commenting on this Pull Request and mention me as [ahmetbozaci](https://github.com/ahmetbozaci), I will receive a notification and will respond._

2021-07-09 21:45 UTC, ahmetbozaci commented on index.html
> +            <span class="headline__nameTwo">I'm a software developer</span></h1>
- [ ] You didn't fix last review. You wrapped this section by `h1 `tag. You should use `h1` tag and delete span in this part.  You should `h1` use tag for `Hey there. I'm Okker John` and you should use `p` tag for `I'm a software developer`

2021-07-09 21:45 UTC, ahmetbozaci commented on style.css
> +  display: flex;
**OPTIONAL**
- [ ] For DRY css cam  use combine duplicate properties. 
You can create class `.d-flex { display: flex}` and use this class in html file.

- For more information about DRY principles you can check this [article](https://www.freecodecamp.org/news/7-important-tips-for-writing-better-css/)

2021-07-09 22:09 UTC, johnspeny commented
@ahmetbozaci have a review and see if its well

2021-07-09 22:10 UTC, johnspeny commented on index.html
> +            <span class="headline__nameTwo">I'm a software developer</span></h1>
fixed

2021-07-09 22:20 UTC, johnspeny commented
@AshakaE have a look at what I have so far. I cant handle rebase at the moment, it has a weird behaviour on my visual studio code cmd that I can't control yet.

2021-07-10 05:41 UTC, mikenath223 approved these changes
Hello there  

Your project is complete!  There is nothing else to say other than... it's time to merge it 🛳 
Congratulations! 🎉 

Happy coding. Cheers! 🚀🚀

If you feel something isn't clear enough you can leave a question or comment in the PR thread.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-10 06:04 UTC, merged