Create Work, About me and Contacts section
johnspeny/JohnSpenyPortifolio pull request #2
Opened 2021-07-10 10:14 UTC by johnspeny

**Work, About, Contacts Section**

1. Created work section with grid and flex
2. About section has flex box with skills
3. Contacts section has forms and social links

2021-07-10 10:53 UTC, Emmyn5600 requested changes
#### Hi @johnspeny :raised_hands:

Good job so far!:clap::clap:
We, however, have some issues to look into before we may move forward but you are almost there!:muscle:

##  Required Changes :recycle::warning: 

* Please you need commits oftentimes instead of pushing all changes at once
* Please follow the [figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1%3A468) to implement the changes requested.

**_Check the comments under the review._**

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2021-07-10 10:53 UTC, Emmyn5600 commented on index.html
> +        </div>
- [ ] The paragraph (e.g., "A daily section ...") is a p tag, Please include the paragraph as it is in the [Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122)

2021-07-10 10:53 UTC, Emmyn5600 commented on index.html
> +                    <button>See Project</button>
- [ ] The paragraph (e.g., "A daily section ...") is a p tag, Please include the paragraph as it is in the [Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122)

2021-07-10 10:53 UTC, Emmyn5600 commented on index.html
> +            </div>
- [ ] - [ ] The paragraph (e.g., "A daily section ...") is a p tag, Please include the paragraph as it is in the [Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122)

2021-07-10 10:53 UTC, Emmyn5600 commented on index.html
> +                </span>
- [ ] The paragraph (e.g., "A daily section ...") is a p tag, Please include the paragraph as it is in the [Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122)

2021-07-10 10:53 UTC, Emmyn5600 commented on index.html
> +                    <button>See Project</button>
- [ ] The paragraph (e.g., "A daily section ...") is a p tag, Please include the paragraph as it is in the [Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122)

2021-07-10 10:53 UTC, Emmyn5600 commented on index.html
> +                    <button>See Project</button>
- [ ] The paragraph (e.g., "A daily section ...") is a p tag, Please include the paragraph as it is in the [Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122)

2021-07-10 10:53 UTC, Emmyn5600 commented on style.css
> +
- [ ] Original
![orig](https://user-images.githubusercontent.com/55635977/125160110-8f84bc80-e17b-11eb-8023-40b71c9edf63.png)

- [ ] Yours
![your](https://user-images.githubusercontent.com/55635977/125160128-9dd2d880-e17b-11eb-8d6c-098fb787541a.png)

* Kindly, Fix that to make yours look the same as the original, for more refer to the [Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122)

2021-07-10 10:53 UTC, Emmyn5600 commented on index.html
> +        </span>
- [ ] Original
![about](https://user-images.githubusercontent.com/55635977/125160258-38cbb280-e17c-11eb-9772-70bbaa06c47c.png)

- [ ] Yours
![yours](https://user-images.githubusercontent.com/55635977/125160264-3d906680-e17c-11eb-9675-b51da9fd386b.png)

* Kindly, Fix that to make yours look the same as the original, for more refer to the [figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122)

2021-07-10 10:53 UTC, Emmyn5600 commented on index.html
> +        <h3>johnspeny@gmail.com</h3>
- [ ] Original
![contac](https://user-images.githubusercontent.com/55635977/125160418-11291a00-e17d-11eb-8c8d-6a42b7eb09d2.png)

- [ ] Yours
![contactyour](https://user-images.githubusercontent.com/55635977/125160427-1c7c4580-e17d-11eb-8388-d69d76392a9b.png)

* Please fix this as well.

2021-07-10 11:10 UTC, johnspeny commented
@Emmyn5600 I am using template 3 from Figma. Please have a look at it.

2021-07-10 18:15 UTC, Emmyn5600 requested changes
#### Hi @johnspeny :raised_hands:

Good job so far!:clap::clap:
We, however, have some issues to look into before we may move forward but you are almost there!:muscle:

##  Required Changes :recycle::warning: 

**_Check the comments under the review._**

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2021-07-10 18:15 UTC, Emmyn5600 commented on index.html
> +                </span>
- [ ] Original
![proj](https://user-images.githubusercontent.com/55635977/125172498-60da0680-e1ba-11eb-9e75-13e1a28a736b.png)

- [ ] Yours

![proj2](https://user-images.githubusercontent.com/55635977/125172493-5455ae00-e1ba-11eb-96d1-fcf38430387c.png)
Hint:
* resize your image to fit into the card
* Make margin-top to your button

2021-07-10 18:15 UTC, Emmyn5600 commented on index.html
> +                    <button>See Project</button>
- [ ] Original
![proj](https://user-images.githubusercontent.com/55635977/125172498-60da0680-e1ba-11eb-9e75-13e1a28a736b.png)

- [ ] Yours

![proj2](https://user-images.githubusercontent.com/55635977/125172493-5455ae00-e1ba-11eb-96d1-fcf38430387c.png)
Hint:
* resize your image to fit into the card
* Make margin-top to your button

2021-07-10 18:15 UTC, Emmyn5600 commented on index.html
> +                    <button>See Project</button>
- [ ] Original
![proj](https://user-images.githubusercontent.com/55635977/125172498-60da0680-e1ba-11eb-9e75-13e1a28a736b.png)

- [ ] Yours

![proj2](https://user-images.githubusercontent.com/55635977/125172493-5455ae00-e1ba-11eb-96d1-fcf38430387c.png)
Hint:
* resize your image to fit into the card
* Make margin-top to your button

2021-07-10 18:15 UTC, Emmyn5600 commented on index.html
> +                    <button>See Project</button>
- [ ] Original
![proj](https://user-images.githubusercontent.com/55635977/125172498-60da0680-e1ba-11eb-9e75-13e1a28a736b.png)

- [ ] Yours

![proj2](https://user-images.githubusercontent.com/55635977/125172493-5455ae00-e1ba-11eb-96d1-fcf38430387c.png)
Hint:
* resize your image to fit into the card
* Make margin-top to your button

2021-07-10 18:15 UTC, Emmyn5600 commented on index.html
> +                    <button>See Project</button>
- [ ] Original
![proj](https://user-images.githubusercontent.com/55635977/125172498-60da0680-e1ba-11eb-9e75-13e1a28a736b.png)

- [ ] Yours

![proj2](https://user-images.githubusercontent.com/55635977/125172493-5455ae00-e1ba-11eb-96d1-fcf38430387c.png)
Hint:
* resize your image to fit into the card
* Make margin-top to your button

2021-07-15 17:19 UTC, ahcodes approved these changes

2021-07-15 21:19 UTC, merged